spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
#    database: mysql
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: info
